node {
    docker.image('maven:3.9.2').inside('-u root') {
        stage('Build') {
            sh 'mvn -B -DskipTests clean package'
        }
        
        stage('Test') {
            try {
                sh 'mvn test'
            } finally {
                junit 'target/surefire-reports/*.xml'
            }
        }
        
        stage('Deliver') {
            sh './jenkins/scripts/deliver.sh'
        }
    }
}